import type { Metadata } from "next";
import "./globals.css";
import { Raleway } from "next/font/google";
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";

const font = Raleway({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Sandesh Subedi | Full-Stack Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className={font.className}>
          <div>
            <Navbar />
          </div>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
